imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: elastica.yml }
    #- { resource: @KromboxMainBundle/Resources/config/validation.yml }
    - { resource: @KromboxMainBundle/Resources/config/admin.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }
    #- { resource: "@Padam87AttributeBundle/Resources/config/config.yml" }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # other form themes
        - 'VichUploaderBundle:Form:fields.html.twig'
    form:
        resources:            
            - 'KromboxMainBundle:Form:map.html.twig'
            - 'KromboxMainBundle:Form:fields.html.twig'
            - LexikFormFilterBundle:Form:form_div_layout.html.twig
            - 'SonataCoreBundle:Form:datepicker.html.twig'
    globals:
        #redis_manager: "@redis.manager"        

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ "FOSCommentBundle", "KromboxMainBundle" ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        mapping_types:
            enum: string
        types:
            StatusType: Krombox\MainBundle\DBAL\Types\StatusType
            DayType: Krombox\MainBundle\DBAL\Types\DayType
            LikeType: Krombox\MainBundle\DBAL\Types\LikeType
            CategoryType: Krombox\MainBundle\DBAL\Types\CategoryType
            PhoneType: Krombox\MainBundle\DBAL\Types\PhoneType
            SocialLinkType: Krombox\MainBundle\DBAL\Types\SocialLinkType
            KitchenType: Krombox\MainBundle\DBAL\Types\KitchenType
            MembershipType: Krombox\MainBundle\DBAL\Types\MembershipType
            MembershipStatusType: Krombox\MainBundle\DBAL\Types\MembershipStatusType
            PaymentStatusType: Krombox\MainBundle\DBAL\Types\PaymentStatusType
#            json: Sonata\Doctrine\Types\JsonType

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
#        entity_managers:
#            default:
#              mappings:
#                    # ApplicationSonataUserBundle: ~
#                    SonataUserBundle: ~
#        entity_managers:
#            default:
#                auto_mapping: true
#                mappings:
#                    gedmo_translatable:
#                        type: annotation
#                        prefix: Gedmo\Translatable\Entity
#                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
#                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
#                        is_bundle: false
        
#stof_doctrine_extensions:
#    orm:
#        default:            
#            timestampable: true
#            sluggable: true
#             translatable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
a2lix_translation_form:
    locale_provider: default       # [1]
    locales: %locales%          # [1-a]
    default_locale: ru             # [1-b]
    required_locales: [ru, en]         # [1-c]
    manager_registry: doctrine      # [2]
    templating: "KromboxMainBundle::Form/fields.html.twig"      # [3  
    
#fos_user:
#    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
#    firewall_name: main
#    user_class: Application\Sonata\UserBundle\Entity\User #Krombox\UserBundle\Entity\User
#    
#    group:
#        group_class:   Application\Sonata\UserBundle\Entity\Group
#        group_manager: sonata.user.orm.group_manager
#        
#    service:
#        user_manager: sonata.user.orm.user_manager
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Krombox\UserBundle\Entity\User
    #user_class:     Application\Sonata\UserBundle\Entity\User


#    group:
#        group_class:   Application\Sonata\UserBundle\Entity\Group
#        group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)
#
#    service:
#        user_manager: sonata.user.orm.user_manager
        
        
#    group:
#        group_class: Application\Sonata\UserBundle\Entity\Group
    
sonata_block:
    #default_contexts: [sonata_page_bundle]
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)    

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
            
sonata_admin:
    title:      Motion Admin Panel
    #title_logo: bundles/acmedemo/img/fancy_acme_logo.png
    security:
        #handler: sonata.admin.security.handler.role
    templates:
        layout:  KromboxMainBundle:SONATA:layout.html.twig    
    
vich_uploader:
    db_driver: orm
    twig:       true
    storage:    flysystem #file_system  or gaufrette or flysystem
    mappings:
#        place_hall_image:
##            uri_prefix:         /images/places
##            upload_destination: place_image_fs #%kernel.root_dir%/../web/images/places
#            uri_prefix:         https://copy.com/thumbs_public/KO2t8RdDRUBpINWa
#            #uri_prefix:         https://copy.com/thumbs_public/xpGFXGkG1T4MzW0r            
#            upload_destination: place_hall_image_fs
#            namer:              vich_uploader.namer_uniqid
#            directory_namer:    place_hall_image_directory_namer
#            inject_on_load:     false
#            delete_on_update:   true
#            delete_on_remove:   true
        category_image:
            #uri_prefix:         /images/places
            #upload_destination: place_image_fs #%kernel.root_dir%/../web/images/places
            uri_prefix:         /images/categories
            upload_destination: category_image_fs
            namer:              vich_uploader.namer_uniqid
            #directory_namer:    category_image_directory_namer
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
        event_image:
            #uri_prefix:         /images/places
            #upload_destination: place_image_fs #%kernel.root_dir%/../web/images/places
            uri_prefix:         https://copy.com/thumbs_public/Hj3JhZ2UKLmimw3X
            upload_destination: event_image_fs
            namer:              vich_uploader.namer_uniqid
            directory_namer:    event_image_directory_namer
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
#        place_image:
#            #uri_prefix:         /images/places
#            #upload_destination: place_image_fs #%kernel.root_dir%/../web/images/places
#            uri_prefix:         https://copy.com/thumbs_public/xpGFXGkG1T4MzW0r
#            upload_destination: place_hall_image_fs
#            namer:              vich_uploader.namer_uniqid
#            directory_namer:    place_image_directory_namer
#            inject_on_load:     true
#            delete_on_update:   true
#            delete_on_remove:   true    
            
oneup_flysystem:
#    cache:
#        my_cache: ~            

    adapters:
#        place_adapter:
#            custom:
#                service: krombox.flysystem.flickr_client
#             copy: 
#                client: flysystem.copy_client
#                prefix: ~
        event_adapter:
             copy: 
                client: flysystem.copy_client
                prefix: ~        
#            local:
#                directory: %kernel.root_dir%/../web/images/places
        category_adapter:
            local:
                directory: %kernel.root_dir%/../web/images/categories

    filesystems:
#        place_filesystem:
#            adapter: place_adapter
#            mount:   place_hall_image_fs
        category_filesystem:
            adapter: category_adapter
            mount:   category_image_fs
        event_filesystem:
            adapter: event_adapter
            mount:   event_image_fs    
            
liip_imagine:
    #data_loader: my_remote_loader
    cache: my_remote_resolver
    data_loader: my_remote_loader
    #cache: ~
    #cache: my_remote_resolver
#    resolvers:
#        default:
#            web_path:
#              web_root: http://www.ultraimg.com
#              cache_prefix: /images
#        my_remote_resolver:
#            web_path:
#              web_root: http://www.ultraimg.com
#              cache_prefix: /images      
#    loaders:
#        default:
#            filesystem:
#                data_root: https://copy.com/thumbs_public/nIdkDSHtsduPhb3E/place_images/

    filter_sets:
        #cache: my_remote_resolver
        #cache: ~
        
        place_logo_thumb:            
            cache: my_remote_resolver
            quality: 90
            filters:
                thumbnail: { size: [250, 250], mode: outbound }
                
        place_image_thumb:            
            cache: my_remote_resolver
            quality: 90
            filters:
                thumbnail: { size: [350, 350], mode: outbound }
            
        place_image_preview_thumb:            
            cache: my_remote_resolver
            quality: 70
            filters:
                thumbnail: { size: [120, 120], mode: outbound }                                
                
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [KromboxMainBundle]
        directories: ["%kernel.root_dir%/../src"]
        
jms_translation:
    configs:
        main:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            #extractors: [alias_of_the_extractor]
            
#jms_di_extra:
#    locations:
#        all_bundles: false
#        bundles: [KromboxMainBundle]
#        directories: ["%kernel.root_dir%/../src"]            
    
lexik_form_filter:
    force_case_insensitivity: false
    
                        
#snc_redis:
#    clients:
#        default:
#            type: predis
#            alias: default
#            dsn: redis://localhost            
        
hwi_oauth:
    connect:
        account_connector: my_user_provider
    http_client:
        verify_peer: false
    fosub:
        username_iterations: 300
        properties:
            vk: vk_id
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    resource_owners:
        vk:
            type:                vkontakte
            client_id:           4896425
            client_secret:       y8oMAf0yVgJds4cipRst
            scope:               offline,email
            
sc_datetimepicker:
    picker: ~
    
genemu_form:
    select2: ~
    image: ~
    
oneup_uploader:
    mappings:
        gallery:
            use_orphanage: true
            frontend: dropzone
            storage:
#                service: id.yy

fos_comment:
    db_driver: orm
    class:
        model:
            comment: Krombox\CommentBundle\Entity\Comment
            thread:  Krombox\CommentBundle\Entity\Thread
            vote:    Krombox\CommentBundle\Entity\Vote
                
    acl: true
    service:
        spam_detection:
            comment: fos_comment.spam_detection.comment.akismet
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: ROLE_USER
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
            
ornicar_akismet:
    api_key:        %akismet_key%
    url:            http://93.78.12.177
    
fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: force

sensio_framework_extra:
    view:    { annotations: false } 
    
lunetics_locale:
  strict_mode: false
  allowed_locales:
    - en
    - ru
  guessing_order:
    - query
    - router
    - session
    - cookie
    - browser
  cookie:
    set_on_change: true
    
matthias_noback_microsoft_translator:
    oauth:
        client_id: "%microsoft_translator.client_id%"
        client_secret: %microsoft_translator.client_secret%    
    
krombox_form_auto_translation:
    auto_translated_locales: %locales%
    locale_provider: default
    templating: "KromboxFormAutoTranslationBundle::default.html.twig"
    
bazinga_geocoder:
    providers:
        google_maps:
            locale:               null
            region:               null
            use_ssl:              true
            api_key:              AIzaSyDzmQiEmu390yCXaB9RQ4jFwXnm_hEJJBI
            
#rezzza_flickr:
#    key: 29f44a3c5eb65e3be1e7ec4dfe6e4a5e
#    secret: f554a6fb7c6b76ce            
    
rezzza_flickr:
    default_client: default
    clients:
        default:
            key: 29f44a3c5eb65e3be1e7ec4dfe6e4a5e
            secret: f554a6fb7c6b76ce
#        second:
#            key: 'my second api key'
#            secret: 'my second api secret'    
            
    
    
