fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        app:
            types:
                place:
                    mappings:
                        id: ~
                        #name: ~
                        nameTranslatableRU: ~
                        nameTranslatableEN: ~
                        #description: ~
                        status: ~
                        #birthdayDiscount: ~
                        is24h: ~
                        city:
                            type: "object"
                            properties:
                                slug: ~
                        categories:
                            type: "object"                            
                            properties:
                                #id: ~
                                slug:
                                    type: string
                                    index: "not_analyzed"
                        placeFilterValues:
                            type: "object"
                            properties:                                
                                slug: ~
                        businessHours:
                            type: "nested"
                            properties:                                
                                dayMonday: ~        
                                dayTuesday: ~
                                dayWednesday: ~
                                dayThursday: ~
                                dayFriday: ~
                                daySaturday: ~
                                daySunday: ~
                                startsAtFormatted:
                                    type: "date"
                                    format: "H:m:s"
                                endsAtFormatted:
                                    type: "date"
                                    format: "H:m:s"
                        businessHoursException:
                            type: "nested"
                            properties:                                                                
                                dayFormatted:
                                    type: "date"
                                    format: "Y-m-d"
                                startsAtFormatted:
                                    type: "date"
                                    format: "H:m:s"
                                endsAtFormatted:
                                    type: "date"
                                    format: "H:m:s"            
#                        services:
#                            type: "object"
#                            properties:                                
#                                slug: ~
#                        menu: 
#                            type: "object"
#                            properties:                                
#                                slug: ~        
                        membershipSubscriptions:
                            type: "nested"
                            properties:                                
                                m_status:
                                    property_path: status
                                membership:
                                    type: "object"
                                    properties:
                                        score: ~
                                        name: ~
#                        ratings:
#                            type: "object"
#                            properties:
#                                rate: ~        
#                        is24h: ~
                        #isWifi: ~
#                        isDelivery: ~
                        rating: ~
                        ratingCount: ~
                        viewsCount: ~
#                        membershipSubscriptions:
#                            type: "object"
#                            properties:
                                #id: ~
                                #type: ~
                                #score: ~
                                #statusSubscription: ~
                    _parent:
                        type: "user"
                        property: "user"
                        identifier: "username"
                    persistence:
                        # the driver can be orm, mongodb or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: Krombox\MainBundle\Entity\Place
                        provider: ~
                        listener: ~
                            #immediate: ~
                        finder: ~
                        repository: Krombox\MainBundle\Repository\Search\PlaceRepository
#                rating:
#                    mappings:
#                        rate: ~
#                    persistence:                        
#                        driver: orm
#                        model: Krombox\MainBundle\Entity\Rating
#                        provider: ~
#                        listener: ~                           
#                        finder: ~
                membershipSubscription:
                    mappings:
                        status: ~
                        membership:
                                    type: "object"
                                    properties:
                                        score: ~
                                        name: ~
                    _parent:
                        type: "place"
                        property: "place"
                        identifier: "id"    
                    persistence:                        
                        driver: orm
                        model: Krombox\MainBundle\Entity\MembershipSubscription
                        provider: ~
                        listener: ~                           
                        finder: ~        
                        #repository: Krombox\MainBundle\Repository\Search\PlaceRepository    
                event:
                    mappings:
                        name: ~
                        description: ~
                        status: ~                        
#                        categories:
#                            type: "object"
#                            properties:
#                                slug: ~                                                        
                    _parent:
                        type: "user"
                        property: "user"
                        identifier: "username"
                    persistence:
                        # the driver can be orm, mongodb or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: Krombox\MainBundle\Entity\Event
                        provider: ~
                        listener: ~
                            #immediate: ~
                        finder: ~
                        repository: Krombox\MainBundle\Repository\Search\EventRepository        
                category:
                    mappings:
                        id: ~
                        #name: ~
                        #description: ~
                        slug: ~
                    persistence:                        
                        driver: orm
                        model: Krombox\MainBundle\Entity\Category
                        provider: ~
                        listener: ~                           
                        finder: ~
                        repository: Krombox\MainBundle\Repository\Search\PlaceRepository
                businessHours:
                    mappings:
                        id: ~
                        dayMonday: ~        
                        dayTuesday: ~
                        dayWednesday: ~
                        dayThursday: ~
                        dayFriday: ~
                        daySaturday: ~
                        daySunday: ~
                        startsAtFormatted:
                            type: "date"
                            format: "H:m:s"
                        endsAtFormatted:
                            type: "date"
                            format: "H:m:s"                        
                    persistence:                        
                        driver: orm
                        model: Krombox\MainBundle\Entity\BusinessHours
                        provider: ~
                        listener: ~                           
                        finder: ~
                        #repository: Krombox\MainBundle\Repository\Search\PlaceRepository
                businessHoursException:
                    mappings:
                        id: ~
                        dayFormatted:
                            type: "date"
                            format: "Y-m-d"
                        startsAtFormatted:
                            type: "date"
                            format: "H:m:s"
                        endsAtFormatted:
                            type: "date"
                            format: "H:m:s"                        
                    persistence:                        
                        driver: orm
                        model: Krombox\MainBundle\Entity\BusinessHoursException
                        provider: ~
                        listener: ~                           
                        finder: ~
                        #repository: Krombox\MainBundle\Repository\Search\PlaceRepository                                
                tag:
                    mappings:                        
                        name: ~                        
                    persistence:                        
                        driver: orm
                        model: Krombox\MainBundle\Entity\MyTag
                        provider: ~
                        listener:                            
                        finder: ~
                        repository: Krombox\MainBundle\Repository\Search\MyTagRepository
                user:
                    mappings:                        
                        username: ~                        
                    persistence:
                        # the driver can be orm, mongodb or propel
                        # listener and finder are not supported by
                        # propel and should be removed
                        driver: orm
                        model: Krombox\UserBundle\Entity\User
                        provider: ~
                        listener:                            
                        finder: ~ 
                        
                city:
                    mappings:
                        nameTranslatableRU: ~
                        nameTranslatableEN: ~
                        slug: ~                        
                    persistence:                        
                        driver: orm
                        model: Krombox\MainBundle\Entity\City
                        provider: ~
                        listener:                            
                        finder: ~
                        repository: Krombox\MainBundle\Repository\Search\CityRepository