Krombox\MainBundle\Entity\Menu:
    type: entity    
    table: p_menu
    #repositoryClass: Krombox\MainBundle\Repository\PlaceRepository
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }    
    fields:        
        name:
            type: string
            nullable: false
        slug:
            type: string
            nullable: false    
            
#    manyToMany:        
#        places:
#            targetEntity: Krombox\MainBundle\Entity\Place
#            mappedBy: kitchens
    lifecycleCallbacks: {}
        #
