Krombox\MainBundle\Entity\ServiceMany:
    type: entity    
    table: service_many
    #repositoryClass: DDI\MainBundle\Repository\NewsRepository    
    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }    
    fields:
        name:
            type: string
        
    manyToOne:
        place:
            targetEntity: Krombox\MainBundle\Entity\Place
            inversedBy: serviceMany
            joinColumn:
                name: place_id
                referencedColumnName: id
                onDelete: cascade
                onUpdate: cascade
    lifecycleCallbacks: {  }