parameters:
    my_user_provider.class:  Krombox\UserBundle\Security\Core\User\FOSUBUserProvider
    
services:    
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: [@fos_user.user_manager,{vk: vk_id}]	