<?php

namespace Krombox\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Krombox\MainBundle\DBAL\Types\CategoryType;
use Krombox\MainBundle\DBAL\Types\StatusType;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function queryCategoriesByType($type, $existed = false){
        $qb = $this->createQueryBuilder('c');
        //var_dump(CategoryType::getReadableValue($type));die();
        if($existed){
            $qb->innerJoin('c.' . strtolower(CategoryType::getReadableValue($type)) . 's', 'cp')
                ->where('cp.status = :status')
                ->setParameter('status', StatusType::VALIDATED)
            ;
        }
        
        $qb->andWhere('c.type = :categoryType')           
            ->setParameter('categoryType', $type);                                                    
        ;                
        
        return $qb;
    }
            
    public function getCategoriesByType($type, $existed = false)
    {
        $qb = $this->queryCategoriesByType($type, $existed);
        $query = $qb->getQuery();        
        
        try {
            $result = $query->getResult();                        
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
                          
        return $result;
    }
}
