<?php

namespace Krombox\MainBundle\Repository;

use Krombox\MainBundle\DBAL\Types\StatusType;
use Doctrine\ORM\EntityRepository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends EntityRepository
{
    public function getEvents($place)
    {
        $qb = $this->createQueryBuilder('e')
                ->where('e.status = :status')
                ->setParameter('status', StatusType::VALIDATED)
        ;
        
        
        if($place){
            $qb->innerJoin('e.place', 'p', 'WITH', 'p.hash = :place')
                ->setParameter('place', $place)
            ;
        }
                                
        $query = $qb->getQuery();        
        
        try {
            $result = $query->getResult();                        
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
                          
        return $result;
    }
}
