<?php

namespace Krombox\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Krombox\MainBundle\DBAL\Types\StatusType;
use Krombox\MainBundle\DBAL\Types\MembershipStatusType;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceFilterValueRepository extends EntityRepository
{
    
    public function queryGet(array $criteria = [])
    {
        $qb = $this->createQueryBuilder('pfv')
            ->leftJoin('pfv.placeFilterKind', 'pfk')
        ;
        //var_dump($criteria);die();
        if(isset($criteria['place']))
        {
            $qb
                ->leftJoin('pfv.places', 'pfvp')
                ->andWhere('pfvp.id = :place_id')
                ->setParameter('place_id', $criteria['place'])
            ;
        }
        
        if(isset($criteria['categories']))
        {
            $qb
                ->leftJoin('pfk.categories', 'pfkc')
                ->andWhere('pfkc.id IN(:categories)')
                ->setParameter('categories', $criteria['categories'])            
                //->orderBy('pfk.id')
            ;
        }
                                
        return $qb;
    }
    
    public function get(array $criteria = []){
        $qb = $this->queryGet($criteria);
        $query = $qb->getQuery();                
        
        try {
            $result = $query->getResult();                        
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
                          
        return $result;
    }

    public function queryPlaceFilterValuesByCategories($categories)
    {                
        $qb = $this->createQueryBuilder('pfv')
                ->leftJoin('pfv.placeFilterKind', 'pfk')
                ->leftJoin('pfk.categories', 'pfkc')
                ->where('pfkc.id IN(:categories)')                
                ->setParameter('categories', $categories)
                ->orderBy('pfk.id')
        ;                
                                
        return $qb;
    }        
    
    public function getPlaceFilterKindByCategories($categories)
    {                
        $qb = $this->queryPlaceFilterKindByCategories($categories);                                                
        $query = $qb->getQuery();                
        
        try {
            $result = $query->getResult();                        
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
                          
        return $result;
    }        
}
